[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin=lib/openzeppelin-contracts/']

vebrbosity =5

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
sepolia={ key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

mumbai = { key = "${POLYGONSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
